# Generated by Django 3.1.6 on 2021-02-06 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Results',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=25)),
                ('frequency', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Result',
            },
        ),
        migrations.CreateModel(
            name='Web_address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=2000)),
            ],
            options={
                'verbose_name': 'Web addresses',
            },
        ),
    ]
